import type { Format } from '@/contexts/catalog/domain/album'

export type RandomAlbum = {
  artist: string
  title: string
  format: Format
  releaseDate: Date
  genres: string[]
  rating: number
}

const RATING = { H90: 4.5, PERFECT: 5 } as const

export const RANDOM_ALBUMS: RandomAlbum[] = [
  {
    artist: 'Ichiko Aoba',
    format: 'LP',
    genres: [
      'Chamber Folk',
      'Singer-Songwriter',
      'Nature Recordings',
      'New Age',
      'Ambient',
    ],
    rating: RATING.PERFECT,
    releaseDate: new Date('2020-12-02'),
    title: 'Windswept Adan',
  },
  {
    artist: 'Jane Remover',
    format: 'LP',
    genres: [
      'Digicore',
      'Experimental Hip Hop',
      'Electronic Dance Music',
      'Rage',
      'Hyperpop',
      'Electroclash',
      'Hard Dance',
      'Bass House',
    ],
    rating: RATING.PERFECT,
    releaseDate: new Date('2025-04-04'),
    title: 'Revengeseekerz',
  },
  {
    artist: 'Keiichi Okabe',
    format: 'LP',
    genres: ['New Age', 'Cinematic Classical', 'Classical Crossover'],
    rating: RATING.PERFECT,
    releaseDate: new Date('2017-03-29'),
    title: 'NieR:Automata (Original Soundtrack)',
  },
  {
    artist: 'Fear Before The March Of Flames',
    format: 'LP',
    genres: [
      'Post-Hardcore',
      'Alternative Rock',
      'Sasscore',
      'Metalcore',
      'Experimental Rock',
      'Emo',
      'Post-Rock',
      'Mathcore',
    ],
    rating: RATING.PERFECT,
    releaseDate: new Date('2006-09-19'),
    title: 'The Always Open Mouth',
  },
  {
    artist: 'Nasum',
    format: 'LP',
    genres: ['Grindcore', 'Metalcore'],
    rating: RATING.PERFECT,
    releaseDate: new Date('2003-05-13'),
    title: 'Helvete',
  },
  {
    artist: 'The Newfound Interest in Connecticut',
    format: 'LP',
    genres: [
      'Midwest Emo',
      'Post-Rock',
      'Math Rock',
      'Post-Hardcore',
      'Field Recordings',
    ],
    rating: RATING.PERFECT,
    releaseDate: new Date('2005-01-01'),
    title: 'Tell Me About the Long Dark Path Home',
  },
  {
    artist: 'Knocked Loose',
    format: 'LP',
    genres: ['Metalcore', 'Beatdown Hardcore'],
    rating: RATING.PERFECT,
    releaseDate: new Date('2024-05-10'),
    title: "You Won't Go Before You're Supposed To",
  },
  {
    artist: 'Serpent Column',
    format: 'LP',
    genres: [
      'Dissonant Black Metal',
      'Black Metal',
      'Avant-Garde Metal',
      'Mathcore',
    ],
    rating: RATING.PERFECT,
    releaseDate: new Date('2019-09-09'),
    title: 'Mirror in Darkness',
  },
  {
    artist: 'Björk',
    format: 'LP',
    genres: [
      'Art Pop',
      'Electronic',
      'Folktronica',
      'Ambient Pop',
      'Glitch Pop',
      'Microsound',
      'Downtempo',
    ],
    rating: RATING.PERFECT,
    releaseDate: new Date('2001-08-18'),
    title: 'Vespertine',
  },
  {
    artist: 'The Fall of Troy',
    format: 'LP',
    genres: [
      'Math Rock',
      'Post-Hardcore',
      'Sasscore',
      'Mathcore',
      'Swancore',
      'Progressive Rock',
      'Mall Screamo',
    ],
    rating: RATING.PERFECT,
    releaseDate: new Date('2005-08-16'),
    title: 'Doppelgänger',
  },
  {
    artist: 'Knocked Loose',
    format: 'EP',
    genres: ['Metalcore', 'Deathcore', 'Beatdown Hardcore'],
    rating: RATING.PERFECT,
    releaseDate: new Date('2021-10-13'),
    title: 'A Tear in the Fabric of Life',
  },
  {
    artist: 'Dissection',
    format: 'LP',
    genres: ['Melodic Black Metal', 'Melodic Death Metal'],
    rating: RATING.PERFECT,
    releaseDate: new Date('1995-11-17'),
    title: "Storm of the Light's Bane",
  },
  {
    artist: 'Converge',
    format: 'LP',
    genres: ['Mathcore', 'Metalcore', 'Hardcore Punk', 'Sludge Metal'],
    rating: RATING.PERFECT,
    releaseDate: new Date('2001-09-04'),
    title: 'Jane Doe',
  },
  {
    artist: 'Asunojokei',
    format: 'LP',
    genres: ['Blackgaze', 'Post-Hardcore', 'Screamo', 'Post-Black Metal'],
    rating: RATING.PERFECT,
    releaseDate: new Date('2022-07-27'),
    title: 'Island',
  },
  {
    artist: 'Thornhill',
    format: 'LP',
    genres: ['Alternative Metal', 'Shoegaze', 'Alternative Rock', 'Djent'],
    rating: RATING.PERFECT,
    releaseDate: new Date('2022-06-03'),
    title: 'Heroine',
  },
  {
    artist: 'Loathe',
    format: 'LP',
    genres: [
      'Alternative Metal',
      'Metalcore',
      'Shoegaze',
      'Djent',
      'Progressive Metalcore',
    ],
    rating: RATING.PERFECT,
    releaseDate: new Date('2020-02-07'),
    title: 'I Let It in and It Took Everything',
  },
  {
    artist: 'Atheist',
    format: 'LP',
    genres: [
      'Technical Death Metal',
      'Progressive Metal',
      'Progressive Death Metal',
      'Technical Thrash Metal',
      'Jazz Fusion',
    ],
    rating: RATING.H90,
    releaseDate: new Date('1991-10-21'),
    title: 'Unquestionable Presence',
  },
  {
    artist: 'Dead Can Dance',
    format: 'LP',
    genres: ['Neoclassical Darkwave', 'Dungeon Synth'],
    rating: RATING.H90,
    releaseDate: new Date('1987-07-27'),
    title: 'Within the Realm of a Dying Sun',
  },
  {
    artist: 'Ichiko Aoba',
    format: 'LP',
    genres: [
      'Singer-Songwriter',
      'Contemporary Folk',
      'Field Recordings',
      'Progressive Folk',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2013-10-23'),
    title: '0',
  },
  {
    artist: 'Neurosis',
    format: 'LP',
    genres: ['Atmospheric Sludge Metal', 'Doom Metal', 'Post-Rock'],
    rating: RATING.H90,
    releaseDate: new Date('1999-05-04'),
    title: 'Times of Grace',
  },
  {
    artist: 'Neurosis',
    format: 'LP',
    genres: ['Atmospheric Sludge Metal', 'Post-Hardcore', 'Avant-Garde Metal'],
    rating: RATING.H90,
    releaseDate: new Date('1992-05-19'),
    title: 'Souls at Zero',
  },
  {
    artist: 'prettifun',
    format: 'LP',
    genres: [
      'Trap',
      'Rage',
      'Pop Rap',
      'Southern Hip Hop',
      'Plugg',
      'Hyperpop',
      'Digicore',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2024-08-01'),
    title: 'Pretti',
  },
  {
    artist: 'Unwound',
    format: 'LP',
    genres: [
      'Indie Rock',
      'Post-Hardcore',
      'Post-Rock',
      'Art Rock',
      'Gothic Rock',
      'Neo-Psychedelia',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2001-04-17'),
    title: 'Leaves Turn Inside You',
  },
  {
    artist: 'Corea',
    format: 'LP',
    genres: ['Screamo', 'Post-Rock', 'Sound Collage', 'Noise'],
    rating: RATING.H90,
    releaseDate: new Date('2004-12-24'),
    title: 'Los peores 7 peores km de mi vida',
  },
  {
    artist: 'Oklou',
    format: 'Mixtape',
    genres: [
      'Alternative R&B',
      'Ambient Pop',
      'Art Pop',
      'UK Bass',
      'Progressive Electronic',
      'Field Recordings',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2020-09-24'),
    title: 'Galore',
  },
  {
    artist: 'Masayoshi Takanaka',
    format: 'LP',
    genres: [
      'Jazz Fusion',
      'Jazz-Rock',
      'Progressive Rock',
      'Fairy Tales',
      'Jazz-Funk',
    ],
    rating: RATING.H90,
    releaseDate: new Date('1981-03-10'),
    title: 'THE RAINBOW GOBLINS',
  },
  {
    artist: 'Thou',
    format: 'LP',
    genres: [
      'Sludge Metal',
      'Doom Metal',
      'Atmospheric Sludge Metal',
      'Drone Metal',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2007-09-21'),
    title: 'Tyrant',
  },
  {
    artist: 'Carcass',
    format: 'LP',
    genres: ['Melodic Death Metal', 'Death Metal', "Death 'n' Roll"],
    rating: RATING.H90,
    releaseDate: new Date('1993-10-18'),
    title: 'Heartwork',
  },
  {
    artist: 'At The Gates',
    format: 'LP',
    genres: ['Melodic Death Metal'],
    rating: RATING.H90,
    releaseDate: new Date('1995-11-14'),
    title: 'Slaughter of the Soul',
  },
  {
    artist: 'Intestine Baalism',
    format: 'LP',
    genres: ['Melodic Death Metal', 'Death Metal'],
    rating: RATING.H90,
    releaseDate: new Date('2003-04-07'),
    title: 'Banquet in the Darkness',
  },
  {
    artist: 'Boris',
    format: 'Live',
    genres: ['Drone Metal', 'Noise Rock', 'Post-Metal', 'Noise'],
    rating: RATING.H90,
    releaseDate: new Date('2021-02-05'),
    title: 'Bootleg -Feedbacker-',
  },
  {
    artist: 'Boris',
    format: 'Live',
    genres: ['Post-Rock', 'Drone Metal', 'Noise', 'Post-Metal', 'Drone'],
    rating: RATING.H90,
    releaseDate: new Date('2021-02-05'),
    title: 'Boris performing "flood"',
  },
  {
    artist: 'Tim Hecker',
    format: 'LP',
    genres: ['Ambient', 'Noise', 'Glitch', 'Drone'],
    rating: RATING.H90,
    releaseDate: new Date('2006-10-16'),
    title: 'Harmony in Ultraviolet',
  },
  {
    artist: 'Maruja',
    format: 'LP',
    genres: [
      'Post-Rock',
      'Post-Punk',
      'Jazz-Rock',
      'Rap Rock',
      'Noise Rock',
      'Post-Hardcore',
      'Art Punk',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2025-09-12'),
    title: 'Pain to Power',
  },
  {
    artist: 'Sweet Trip',
    format: 'LP',
    genres: [
      'Dream Pop',
      'Indie Pop',
      'Indie Rock',
      'Progressive Pop',
      'Indietronica',
      'Neo-Psychedelia',
      'Twee Pop',
      'Shoegaze',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2009-09-28'),
    title: 'You Will Never Know Why',
  },
  {
    artist: 'BUCK-TICK',
    format: 'LP',
    genres: [
      'Alternative Rock',
      'Visual kei',
      'Gothic Rock',
      'Industrial Rock',
      'New Wave',
      'Post-Punk',
    ],
    rating: RATING.H90,
    releaseDate: new Date('1992-03-21'),
    title: '殺シノ調ベ: This Is NOT Greatest Hits',
  },
  {
    artist: 'Tokyo Jihen',
    format: 'LP',
    genres: ['Jazz-Rock', 'J-Rock', 'Pop Rock', 'Art Pop'],
    rating: RATING.H90,
    releaseDate: new Date('2006-01-25'),
    title: 'Adult',
  },
  {
    artist: 'Tokyo Jihen',
    format: 'LP',
    genres: ['Art Rock', 'J-Rock', 'Jazz-Rock', 'Noise Rock'],
    rating: RATING.H90,
    releaseDate: new Date('2004-11-25'),
    title: 'Education',
  },
  {
    artist: 'Lucy Bedroque',
    format: 'LP',
    genres: [
      'Rage',
      'Experimental Hip Hop',
      'Digicore',
      'Cloud Rap',
      'Glitch Hop',
      'Electronic Dance Music',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2025-05-16'),
    title: 'Unmusique',
  },
  {
    artist: 'Deafheaven',
    format: 'LP',
    genres: ['Blackgaze', 'Post-Black Metal', 'Post-Rock', 'Black Metal'],
    rating: RATING.H90,
    releaseDate: new Date('2025-03-28'),
    title: 'Lonely People With Power',
  },
  {
    artist: 'NMIXX',
    format: 'EP',
    genres: [
      'K-Pop',
      'Alt-Pop',
      'Pop Rap',
      'Contemporary R&B',
      'Trap [EDM]',
      'Alternative R&B',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2025-03-17'),
    title: 'Fe3O4: FORWARD',
  },
  {
    artist: 'Circa Survive',
    format: 'LP',
    genres: [
      'Post-Hardcore',
      'Alternative Rock',
      'Emo',
      'Swancore',
      'Progressive Rock',
      'Post-Rock',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2005-04-19'),
    title: 'Juturna',
  },
  {
    artist: 'Whirr',
    format: 'LP',
    genres: ['Shoegaze', 'Dream Pop', 'Noise Pop'],
    rating: RATING.H90,
    releaseDate: new Date('2024-12-25'),
    title: 'Raw Blue',
  },
  {
    artist: 'Misery Signals',
    format: 'LP',
    genres: [
      'Metalcore',
      'Post-Hardcore',
      'Melodic Metalcore',
      'Emo',
      'Progressive Metalcore',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2004-06-01'),
    title: 'Of Malice and the Magnum Heart',
  },
  {
    artist: 'Ringo Sheena',
    format: 'LP',
    genres: [
      'J-Rock',
      'Noise Pop',
      'Art Pop',
      'Progressive Pop',
      'Neo-Psychedelia',
      'Art Rock',
      'Post-Grunge',
      'Chamber Pop',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2000-03-31'),
    title: 'Winning Strip',
  },
  {
    artist: 'Summoning',
    format: 'LP',
    genres: ['Atmospheric Black Metal', 'Dungeon Synth'],
    rating: RATING.H90,
    releaseDate: new Date('1995-10-16'),
    title: 'Minas Morgul',
  },
  {
    artist: 'Counterparts',
    format: 'EP',
    genres: ['Metalcore', 'Deathcore'],
    rating: RATING.H90,
    releaseDate: new Date('2024-11-07'),
    title: 'Heaven Let Them Die',
  },
  {
    artist: 'Celtic Frost',
    format: 'LP',
    genres: [
      'Doom Metal',
      'Gothic Metal',
      'Avant-Garde Metal',
      'Sludge Metal',
      'Black Metal',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2006-05-29'),
    title: 'Monotheist',
  },
  {
    artist: 'Fear Before The March Of Flames',
    format: 'LP',
    genres: ['Post-Hardcore', 'Metalcore', 'Sasscore', 'Mathcore', 'Screamo'],
    rating: RATING.H90,
    releaseDate: new Date('2004-09-07'),
    title: 'Art Damage',
  },
  {
    artist: 'Killing Me Softly',
    format: 'LP',
    genres: [
      'Metalcore',
      'Melodic Metalcore',
      'Screamo',
      'Mathcore',
      'Post-Hardcore',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2023-12-01'),
    title: 'Autumn Lost in Silence',
  },
  {
    artist: 'Wormrot',
    format: 'LP',
    genres: ['Grindcore', 'Crust Punk'],
    rating: RATING.H90,
    releaseDate: new Date('2016-10-14'),
    title: 'Voices',
  },
  {
    artist: 'Spectral Wound',
    format: 'LP',
    genres: ['Black Metal', 'Melodic Black Metal', "Black 'n' Roll"],
    rating: RATING.H90,
    releaseDate: new Date('2024-08-23'),
    title: 'Songs of Blood and Mire',
  },
  {
    artist: 'Gospel',
    format: 'LP',
    genres: ['Post-Hardcore', 'Screamo', 'Math Rock', 'Progressive Rock'],
    rating: RATING.H90,
    releaseDate: new Date('2005-05-24'),
    title: 'The Moon Is a Dead World',
  },
  {
    artist: 'CQ',
    format: 'LP',
    genres: ['Shoegaze', 'Alternative Metal', 'J-Rock', 'Post-Hardcore'],
    rating: RATING.H90,
    releaseDate: new Date('2016-11-06'),
    title: 'Communication, Cultural, Curiosity Quotient',
  },
  {
    artist: 'Rivers of Nihil',
    format: 'LP',
    genres: [
      'Progressive Metal',
      'Progressive Death Metal',
      'Jazz Fusion',
      'Technical Death Metal',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2018-03-16'),
    title: 'Where Owls Know My Name',
  },
  {
    artist: 'DIR EN GREY',
    format: 'LP',
    genres: [
      'Avant-Garde Metal',
      'Progressive Metal',
      'Alternative Metal',
      'Deathcore',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2011-08-02'),
    title: 'DUM SPIRO SPERO',
  },
  {
    artist: 'ARTMS',
    format: 'LP',
    genres: [
      'K-Pop',
      'Contemporary R&B',
      'Dance-Pop',
      'Synthpop',
      'Future Bass',
      'Alt-Pop',
      'UK Garage',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2024-05-31'),
    title: 'Dall',
  },
  {
    artist: 'Dreamwell',
    format: 'LP',
    genres: [
      'Post-Hardcore',
      'Screamo',
      'Metalcore',
      'Post-Rock',
      'Atmospheric Black Metal',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2023-10-20'),
    title: 'In My Saddest Dreams, I Am Beside You',
  },
  {
    artist: 'Whirr',
    format: 'LP',
    genres: ['Shoegaze', 'Dream Pop', 'Slowcore'],
    rating: RATING.H90,
    releaseDate: new Date('2019-10-29'),
    title: 'Feels Like You',
  },
  {
    artist: 'Maruja',
    format: 'EP',
    genres: [
      'Post-Punk',
      'Post-Rock',
      'Jazz-Rock',
      'Art Punk',
      'Post-Hardcore',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2024-04-26'),
    title: "Connla's Well",
  },
  {
    artist: 'My Chemical Romance',
    format: 'LP',
    genres: [
      'Post-Hardcore',
      'Emo-Pop',
      'Pop Punk',
      'Mall Screamo',
      'Melodic Hardcore',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2004-06-08'),
    title: 'Three Cheers for Sweet Revenge',
  },
  {
    artist: 'billy woods',
    format: 'LP',
    genres: [
      'Abstract Hip Hop',
      'Jazz Rap',
      'Conscious Hip Hop',
      'East Coast Hip Hop',
      'Experimental Hip Hop',
      'Boom Bap',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2023-05-05'),
    title: 'Maps',
  },
  {
    artist: 'A Tribe Called Quest',
    format: 'LP',
    genres: ['Jazz Rap', 'Boom Bap', 'East Coast Hip Hop', 'Conscious Hip Hop'],
    rating: RATING.H90,
    releaseDate: new Date('1993-11-09'),
    title: 'Midnight Marauders',
  },
  {
    artist: 'Björk',
    format: 'LP',
    genres: [
      'Art Pop',
      'Electronic',
      'Trip Hop',
      'Glitch Pop',
      'IDM',
      'Chamber Pop',
    ],
    rating: RATING.H90,
    releaseDate: new Date('1997-09-22'),
    title: 'Homogenic',
  },
  {
    artist: 'Bloodbath',
    format: 'LP',
    genres: ['Death Metal', 'Melodic Death Metal'],
    rating: RATING.H90,
    releaseDate: new Date('2004-09-27'),
    title: 'Nightmares Made Flesh',
  },
  {
    artist: 'yeule',
    format: 'LP',
    genres: [
      'Ambient Pop',
      'Synthpop',
      'Ambient',
      'Glitch Pop',
      'Chillwave',
      'Ambient House',
      'Chillout',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2019-10-25'),
    title: 'Serotonin II',
  },
  {
    artist: "Racionais MC's",
    format: 'LP',
    genres: [
      'Conscious Hip Hop',
      'Hardcore Hip Hop',
      'Boom Bap',
      'Spoken Word',
      'G-Funk',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2002-05-24'),
    title: 'Nada Como um Dia Após o Outro Dia',
  },
  {
    artist: "Racionais MC's",
    format: 'LP',
    genres: [
      'Conscious Hip Hop',
      'Boom Bap',
      'Hardcore Hip Hop',
      'Gangsta Rap',
      'Political Hip Hop',
      'G-Funk',
    ],
    rating: RATING.H90,
    releaseDate: new Date('1997-12-20'),
    title: 'Sobrevivendo no Inferno',
  },
  {
    artist: 'my bloody valentine',
    format: 'LP',
    genres: ['Shoegaze', 'Noise Pop', 'Dream Pop', 'Neo-Psychedelia'],
    rating: RATING.H90,
    releaseDate: new Date('1991-11-04'),
    title: 'loveless',
  },
  {
    artist: 'Maruja',
    format: 'EP',
    genres: [
      'Art Rock',
      'Post-Rock',
      'Art Punk',
      'Post-Punk',
      'Post-Hardcore',
      'Jazz-Rock',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2023-03-17'),
    title: 'Knocknarea',
  },
  {
    artist: 'Perfume',
    format: 'LP',
    genres: [
      'J-Pop',
      'Electropop',
      'Dance-Pop',
      'Electro House',
      'Nu-Disco',
      'Synthpop',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2022-07-27'),
    title: 'PLASMA',
  },
  {
    artist: 'BABYMETAL',
    format: 'LP',
    genres: [
      'Alternative Metal',
      'Trance Metal',
      'Kawaii Metal',
      'J-Pop',
      'Melodic Death Metal',
      'Power Metal',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2014-02-26'),
    title: 'BABYMETAL',
  },
  {
    artist: 'Orchid',
    format: 'LP',
    genres: ['Emoviolence', 'Screamo'],
    rating: RATING.H90,
    releaseDate: new Date('2000-12-04'),
    title: 'Dance Tonight! Revolution Tomorrow!',
  },
  {
    artist: 'Orchid',
    format: 'LP',
    genres: ['Emoviolence', 'Screamo'],
    rating: RATING.H90,
    releaseDate: new Date('1999-06-21'),
    title: 'Chaos Is Me',
  },
  {
    artist: 'Perfume',
    format: 'LP',
    genres: [
      'Dance-Pop',
      'Electropop',
      'J-Pop',
      'Electro House',
      'Synthpop',
      'Funky House',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2008-04-16'),
    title: 'GAME',
  },
  {
    artist: 'Signs of the Swarm',
    format: 'LP',
    genres: ['Deathcore', 'Slam Death Metal'],
    rating: RATING.H90,
    releaseDate: new Date('2017-11-03'),
    title: 'The Disfigurement of Existence',
  },
  {
    artist: 'd.silvestre',
    format: 'LP',
    genres: ['Beat Bruxaria', 'Power Noise', 'Industrial Hardcore'],
    rating: RATING.H90,
    releaseDate: new Date('2023-07-07'),
    title: 'ESPANTA GRINGO',
  },
  {
    artist: 'Alexisonfire',
    format: 'LP',
    genres: [
      'Post-Hardcore',
      'Emo',
      'Mall Screamo',
      'Screamo',
      'Melodic Hardcore',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2002-10-31'),
    title: 'Alexisonfire',
  },
  {
    artist: 'La Dispute',
    format: 'LP',
    genres: ['Post-Hardcore', 'Emo', 'Screamo', 'Poetry'],
    rating: RATING.H90,
    releaseDate: new Date('2011-10-04'),
    title: 'Wildlife',
  },
  {
    artist: 'Unlucky Morpheus',
    format: 'EP',
    genres: [
      'Power Metal',
      'Symphonic Metal',
      'Neoclassical Metal',
      'Progressive Metal',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2015-04-26'),
    title: 'Vampir',
  },
  {
    artist: 'Fleshwater',
    format: 'LP',
    genres: ['Alternative Metal', 'Post-Hardcore', 'Shoegaze'],
    rating: RATING.H90,
    releaseDate: new Date('2022-11-04'),
    title: "We're Not Here to Be Loved",
  },
  {
    artist: 'Counterparts',
    format: 'LP',
    genres: ['Melodic Hardcore', 'Metalcore', 'Emo', 'Post-Hardcore'],
    rating: RATING.H90,
    releaseDate: new Date('2013-07-22'),
    title: 'The Difference Between Hell and Home',
  },
  {
    artist: 'Knocked Loose',
    format: 'LP',
    genres: ['Metalcore', 'Beatdown Hardcore', 'Deathcore'],
    rating: RATING.H90,
    releaseDate: new Date('2019-08-23'),
    title: 'A Different Shade of Blue',
  },
  {
    artist: 'Knocked Loose',
    format: 'LP',
    genres: ['Beatdown Hardcore', 'Metalcore'],
    rating: RATING.H90,
    releaseDate: new Date('2016-09-16'),
    title: 'Laugh Tracks',
  },
  {
    artist: 'Knocked Loose',
    format: 'EP',
    genres: ['Beatdown Hardcore', 'Metalcore'],
    rating: RATING.H90,
    releaseDate: new Date('2014-06-13'),
    title: 'Pop Culture',
  },
  {
    artist: 'Foreign Hands',
    format: 'EP',
    genres: ['Metalcore', 'Emo', 'Melodic Metalcore', 'Post-Hardcore'],
    rating: RATING.H90,
    releaseDate: new Date('2022-02-18'),
    title: 'Bleed the Dream',
  },
  {
    artist: 'Like Moths To Flames',
    format: 'LP',
    genres: ['Metalcore', 'Progressive Metalcore', 'Djent', 'Post-Hardcore'],
    rating: RATING.H90,
    releaseDate: new Date('2020-10-30'),
    title: 'No Eternity in Gold',
  },
  {
    artist: 'yeule',
    format: 'LP',
    genres: [
      'Dream Pop',
      'Indietronica',
      'Glitch Pop',
      'Noise Pop',
      'Shoegaze',
      'Indie Rock',
      'Neo-Psychedelia',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2023-09-22'),
    title: 'softscars',
  },
  {
    artist: 'Deafheaven',
    format: 'LP',
    genres: [
      'Blackgaze',
      'Post-Black Metal',
      'Post-Rock',
      'Shoegaze',
      'Screamo',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2013-06-11'),
    title: 'Sunbather',
  },
  {
    artist: 'Vein',
    format: 'LP',
    genres: ['Mathcore', 'Nu-Metalcore', 'Metalcore', 'Alternative Metal'],
    rating: RATING.H90,
    releaseDate: new Date('2018-06-22'),
    title: 'Errorzone',
  },
  {
    artist: 'Static Dress',
    format: 'LP',
    genres: [
      'Post-Hardcore',
      'Mall Screamo',
      'Metalcore',
      'Alternative Metal',
      'Emo-Pop',
      'Alternative Rock',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2022-05-18'),
    title: 'Rouge Carpet Disaster',
  },
  {
    artist: 'tripleS',
    format: 'EP',
    genres: [
      'K-Pop',
      'Dance-Pop',
      'Contemporary R&B',
      'Future Bass',
      'UK Garage',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2023-08-17'),
    title: 'MUHAN',
  },
  {
    artist: 'Akini Jing',
    format: 'LP',
    genres: [
      'Art Pop',
      'Mandopop',
      'Electronic',
      'IDM',
      'Synthpop',
      'Glitch Pop',
      'Post-Industrial',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2022-07-25'),
    title: 'Endless Farewell',
  },
  {
    artist: 'Amaarae',
    format: 'LP',
    genres: [
      'Afrobeats',
      'Alt R&B',
      'Dance-Pop',
      'Neo-Psychedelia',
      'Amapiano',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2023-06-09'),
    title: 'Fountain Baby',
  },
  {
    artist: 'Holding Absence',
    format: 'LP',
    genres: ['Post-Hardcore', 'Alternative Rock', 'Emo-Pop'],
    rating: RATING.H90,
    releaseDate: new Date('2021-04-16'),
    title: 'The Greatest Mistake of My Life',
  },
  {
    artist: 'The Home Team',
    format: 'LP',
    genres: ['Pop Rock', 'Pop Punk', 'Funk Rock'],
    rating: RATING.H90,
    releaseDate: new Date('2021-10-22'),
    title: 'Slow Bloom',
  },
  {
    artist: 'The Devil Wears Prada',
    format: 'LP',
    genres: [
      'Metalcore',
      'Alternative Metal',
      'Post-Hardcore',
      'Alternative Rock',
      'Emo',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2022-09-16'),
    title: 'Color Decay',
  },
  {
    artist: 'BÉBE YANA',
    format: 'EP',
    genres: [
      'K-Pop',
      'Contemporary R&B',
      '2-Step',
      'Alternative R&B',
      'Future Bass',
      'Liquid Drum and Bass',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2022-06-14'),
    title: 'Space Mulan',
  },
  {
    artist: 'CSR',
    format: 'EP',
    genres: [
      'Synthpop',
      'K-Pop',
      'Dance-Pop',
      'Electropop',
      'Nu-Disco',
      'Synth Funk',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2022-07-28'),
    title: 'Sequence: 7272',
  },
  {
    artist: 'Cattle Decapitation',
    format: 'LP',
    genres: ['Deathgrind', 'Brutal Death Metal', 'Technical Death Metal'],
    rating: RATING.H90,
    releaseDate: new Date('2012-05-08'),
    title: 'Monolith of Inhumanity',
  },
  {
    artist: 'NewJeans',
    format: 'EP',
    genres: [
      'K-Pop',
      'Contemporary R&B',
      'Dance-Pop',
      '2-Step',
      'Liquid Drum and Bass',
      'Future Garage',
      'Alternative R&B',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2023-07-21'),
    title: 'Get Up',
  },
  {
    artist: 'fromjoy',
    format: 'LP',
    genres: [
      'Metalcore',
      'Mathcore',
      'Atmospheric Drum and Bass',
      'Post-Metal',
      'Vapor',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2023-04-28'),
    title: 'fromjoy',
  },
  {
    artist: 'ODD EYE CIRCLE',
    format: 'EP',
    genres: [
      'K-Pop',
      'Future Bass',
      'Dance-Pop',
      'Synthpop',
      'Contemporary R&B',
      'Electropop',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2017-10-31'),
    title: 'Max & Match',
  },
  {
    artist: 'MASS OF THE FERMENTING DREGS',
    format: 'LP',
    genres: [
      'J-Rock',
      'Post-Hardcore',
      'Noise Rock',
      'Post-Punk Revival',
      'Shoegaze',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2009-01-21'),
    title: 'World Is Yours',
  },
  {
    artist: 'Red Velvet',
    format: 'LP',
    genres: [
      'K-Pop',
      'Contemporary R&B',
      'Trap [EDM]',
      'Dance-Pop',
      'Alternative R&B',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2017-11-17'),
    title: 'Perfect Velvet',
  },
  {
    artist: 'fromis_9',
    format: 'LP',
    genres: [
      'K-Pop',
      'Dance-Pop',
      'Contemporary R&B',
      'Future Bass',
      'Nu-Disco',
      'Future House',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2023-06-05'),
    title: 'Unlock My World',
  },
  {
    artist: 'Thornhill',
    format: 'LP',
    genres: ['Progressive Metalcore', 'Alternative Metal', 'Djent'],
    rating: RATING.H90,
    releaseDate: new Date('2019-10-25'),
    title: 'The Dark Pool',
  },
  {
    artist: 'Wonder Girls',
    format: 'LP',
    genres: [
      'K-Pop',
      'Synthpop',
      'Dance-Pop',
      'Electro-Disco',
      'Freestyle',
      'Contemporary R&B',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2015-08-03'),
    title: 'REBOOT',
  },
  {
    artist: 'Billlie',
    format: 'EP',
    genres: [
      'K-Pop',
      'Dance-Pop',
      'Synthpop',
      'Future Bass',
      'Nu-Disco',
      'Synth Funk',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2023-03-28'),
    title: 'the Billage of perception: chapter three',
  },
  {
    artist: 'tripleS',
    format: 'EP',
    genres: [
      'K-Pop',
      'Dance-Pop',
      'New Jack Swing',
      'Synthpop',
      'Contemporary R&B',
      'Electropop',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2023-05-04'),
    title: 'AESTHETIC',
  },
  {
    artist: 'Shadow of Intent',
    format: 'LP',
    genres: [
      'Deathcore',
      'Melodic Death Metal',
      'Symphonic Metal',
      'Technical Death Metal',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2019-08-16'),
    title: 'Melancholy',
  },
  {
    artist: 'JPEGMAFIA & Danny Brown',
    format: 'LP',
    genres: [
      'Experimental Hip Hop',
      'Hardcore Hip Hop',
      'Glitch Hop',
      'Industrial Hip Hop',
      'Jazz Rap',
      'Dariacore',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2023-03-24'),
    title: 'SCARING THE HOES',
  },
  {
    artist: 'Invent Animate',
    format: 'LP',
    genres: [
      'Djent',
      'Progressive Metalcore',
      'Metalcore',
      'Alternative Metal',
      'Post-Hardcore',
      'Thall',
    ],
    rating: RATING.H90,
    releaseDate: new Date('2023-03-17'),
    title: 'Heavener',
  },
  {
    artist: 'Movements',
    format: 'LP',
    genres: ['Emo', 'Post-Hardcore', 'Alternative Rock'],
    rating: RATING.H90,
    releaseDate: new Date('2017-10-20'),
    title: 'Feel Something',
  },
]
