export const ErrorCode = {
  CONFLICT_ERROR: 'CONFLICT_ERROR',
  EMPTY_VALUE: 'EMPTY_VALUE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_DATE: 'INVALID_DATE',
  INVALID_FORMAT: 'INVALID_FORMAT',
  INVALID_LINK: 'INVALID_LINK',
  INVALID_PAGINAION: 'INVALID_PAGINAION',
  NOT_FOUND: 'NOT_FOUND',
} as const

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode]
